"""Closed v1 native-status vocabulary."""

RUN_STATUSES = ("error", "no-op", "partial success", "skipped", "success")
TEST_STATUSES = ("error", "fail", "pass", "skipped", "warn")
NATIVE_STATUSES = tuple(sorted(set(RUN_STATUSES) | set(TEST_STATUSES)))

MAX_REPORT_ISSUES = 20
ISSUE_PRECEDENCE = (
    "DBT_MANIFEST_SIZE_LIMIT_EXCEEDED",
    "DBT_RUN_RESULTS_SIZE_LIMIT_EXCEEDED",
    "DBT_MANIFEST_JSON_INVALID",
    "DBT_RUN_RESULTS_JSON_INVALID",
    "DBT_MANIFEST_JSON_DUPLICATE_KEY",
    "DBT_RUN_RESULTS_JSON_DUPLICATE_KEY",
    "DBT_MANIFEST_JSON_NESTING_LIMIT_EXCEEDED",
    "DBT_RUN_RESULTS_JSON_NESTING_LIMIT_EXCEEDED",
    "DBT_MANIFEST_SCHEMA_INVALID",
    "DBT_RUN_RESULTS_SCHEMA_INVALID",
    "DBT_SCHEMA_VERSION_UNSUPPORTED",
    "DBT_CORE_VERSION_UNSUPPORTED",
    "DBT_INVOCATION_ID_INVALID",
    "DBT_INVOCATION_ID_MISMATCH",
    "DBT_ADAPTER_TYPE_UNSUPPORTED",
    "DBT_COMMAND_UNSUPPORTED",
    "DBT_EMPTY_EXECUTION",
    "DBT_RESULTS_DUPLICATE_ID",
    "DBT_RESULT_ID_UNRESOLVED",
    "DBT_RESULT_ID_UNSUPPORTED_RESOURCE",
    "DBT_RESULT_ID_AMBIGUOUS",
    "DBT_MANIFEST_RESOURCE_ID_MISMATCH",
    "DBT_RESULT_RESOURCE_TYPE_UNSUPPORTED",
    "DBT_RESULT_STATUS_UNSUPPORTED",
    "DBT_TIMING_INVALID",
    "DBT_FAILURE_COUNT_INVALID",
)
